version: '3.8'

services:
  avito-task:
    restart: always
    build: ./
    command: ./avito-task
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=password

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5436:5432"
