basePath: /
definitions:
  avito.Operation:
    properties:
      dateTime:
        type: string
      operation_type:
        type: string
      segment_name:
        type: string
      userId:
        type: integer
    type: object
  avito.Segment:
    properties:
      segment_name:
        type: string
    required:
    - segment_name
    type: object
  avito.User:
    properties:
      added:
        type: string
      expiry:
        type: string
      segment_name:
        type: string
      userId:
        type: integer
    required:
    - segment_name
    - userId
    type: object
  avito.UserInfo:
    properties:
      end:
        type: string
      start:
        type: string
      userId:
        type: integer
    required:
    - end
    - start
    - userId
    type: object
  handler.customError:
    properties:
      message:
        type: string
    type: object
  handler.getAllUserOperationsResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/avito.Operation'
        type: array
    type: object
  handler.getAllUserSegmentsResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/avito.Segment'
        type: array
    type: object
  handler.statusResponse:
    properties:
      status:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: API Application task for backend trainee position
  title: Avito Trainee Application
  version: "1.0"
paths:
  /api/getUserSegments:
    post:
      consumes:
      - application/json
      description: Получение всех сегментов пользователя
      operationId: get-user-segments
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.getAllUserSegmentsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.customError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.customError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.customError'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.customError'
      summary: getUserSegments
      tags:
      - segment
  /api/segments:
    delete:
      consumes:
      - application/json
      description: Удаление сегмента
      operationId: delete-segment
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.statusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.customError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.customError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.customError'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.customError'
      summary: deleteSegment
      tags:
      - segment
    post:
      consumes:
      - application/json
      description: Создание нового сегмента
      operationId: create-segment
      parameters:
      - description: segment data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/avito.Segment'
      produces:
      - application/json
      responses:
        "200":
          description: response
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.customError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.customError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.customError'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.customError'
      summary: createSegment
      tags:
      - segment
  /api/userInfo/:
    post:
      consumes:
      - application/json
      description: Получение информации о добавлении и удалении пользователя в сегменты
        во временном промежутке
      operationId: get-user-info
      parameters:
      - description: user operations data
        in: body
        name: usr
        required: true
        schema:
          $ref: '#/definitions/avito.UserInfo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.getAllUserOperationsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.customError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.customError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.customError'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.customError'
      summary: getUserInfo
      tags:
      - users
  /api/users/:
    delete:
      consumes:
      - application/json
      description: Удаление пользователя из сегмента
      operationId: delete-user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.statusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.customError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.customError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.customError'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.customError'
      summary: deleteUser
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Добавление и удаление пользователя в указанные сегменты
      operationId: create-user
      parameters:
      - description: user data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/avito.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.statusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.customError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.customError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.customError'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.customError'
      summary: createUser
      tags:
      - users
swagger: "2.0"
