basePath: /
definitions:
  avito.Segment:
    properties:
      segment_name:
        type: string
    required:
    - segment_name
    type: object
  handler.customError:
    properties:
      message:
        type: string
    type: object
  handler.getAllUserSegmentsResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/avito.Segment'
        type: array
    type: object
  handler.statusResponse:
    properties:
      status:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: API Application task for backend trainee position
  title: Avito Trainee Application
  version: "1.0"
paths:
  /api/getUserInfo:
    post:
      consumes:
      - application/json
      description: Создание нового сегмента
      operationId: create-segment
      parameters:
      - description: segment data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/avito.Segment'
      produces:
      - application/json
      responses:
        "200":
          description: response
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.customError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.customError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.customError'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.customError'
      summary: createSegment
      tags:
      - segment
  /api/getUserSegments:
    post:
      consumes:
      - application/json
      description: Получение всех пользователя
      operationId: get-user-segments
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.getAllUserSegmentsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.customError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.customError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.customError'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.customError'
      summary: getUserSegments
      tags:
      - segment
  /api/segments:
    delete:
      consumes:
      - application/json
      description: Удаление сегмента
      operationId: delete-segment
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.statusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.customError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.customError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.customError'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.customError'
      summary: deleteSegment
      tags:
      - segment
    post:
      consumes:
      - application/json
      description: Создание нового сегмента
      operationId: create-segment
      parameters:
      - description: segment data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/avito.Segment'
      produces:
      - application/json
      responses:
        "200":
          description: response
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.customError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.customError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.customError'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.customError'
      summary: createSegment
      tags:
      - segment
swagger: "2.0"
